spark:
  app_name: reorder_test_v2
pipeline:
  type: ParquetWriter
  shuffle: false
  mode: overwrite
  output_path: /data/output/group_reorder_test
  child_configs:
    - type: InterleavedReorder
      group_col: type
      type_num: 2
      score_cols:
        - "score"
        - "fasttext_score"
      ascending: true
      child_configs:
        - type: UnionByName
          allow_missing_columns: true
          child_configs:
            - type: AddConstants
              constant_list:
                - 0
              column_list:
                - "type"
              child_configs:
                - type: ParquetReader
                  input_path: "/data/sample/fineweb_chinese.parquet"
            - type: AddConstants
              constant_list:
                - 1
              column_list:
                - "type"
              child_configs:
                - type: ParquetReader
                  input_path: "/data/sample/dclm_subset.parquet"
