spark:
  app_name: read_write
pipeline:
  type: ParquetWriter
  output_path: /home/dclm-rw-output
  child_configs:
    - type: ParquetReader
      input_path: "/home/data/dclm-baseline-1.0-parquet/filtered/OH_eli5_vs_rw_v2_bigram_200k_train/fasttext_openhermes_reddit_eli5_vs_rw_v2_bigram_200k_train/processed_data/global-shard_01_of_10/local-shard_0_of_10/shard_0000000[0-9]_processed.parquet"
