spark:
  app_name: shuffle
pipeline:
  type: Visualizer
  num_rows: 10
  vertical: true
  child_configs:
    - type: Shuffler
      child_configs:
        - type: ParquetReader
          input_path: "/data/sample/scored_input.parquet"
          num_parallel: 2
